# Generated by Django 5.0.4 on 2024-04-17 01:32

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='photos/%Y/%M/%D', verbose_name='Post Picture'),
        ),
    ]
