# Generated by Django 4.0.3 on 2024-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_options_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_verified_email',
            field=models.BooleanField(default=True),
        ),
    ]
